---
- name: "Infra Orchestration"
  hosts: localhost
  gather_facts: false
  become: true
  connection: local

  tasks:
  - name: deploy infra
    terraform:
      force_init: yes
      project_path: '{{playbook_dir}}'
      lock: true
      state: present
    register: task_result
    until: task_result | succeeded
    retries: 5
    delay: 1



  
