---
- name: "Infra Orchestration"
  hosts: vm1
  gather_facts: false
  become: true
  connection: local

  tasks:
  - name: deploy infra
    terraform:
      project_path: '/opt/stack/cloud-automation/terraform/snat'
      lock: true
      state: present



  
