---
- name: "Infra Orchestration"
  hosts: localhost
  gather_facts: false
  become: true
  connection: local

  tasks:
  - name: deploy infra
    terraform:
      #project_path: '/opt/stack/cloud-automation/terraform/snat'
      force_init: yes
      project_path: '{{playbook_dir}}'
      lock: true
      state: present



  
