---
- name: "Delete Orchestration"
  hosts: localhost
  gather_facts: false
  become: true
  connection: local

  tasks:
  - name: destroy infra
    terraform:
      project_path: '{{playbook_dir}}'
      lock: true
      state: absent
