---
- name: "Populate Ansible Inventory/hosts file"
  hosts: localhost
  gather_facts: false
  become: true
  connection: local
  tasks:
  - name: create Inventory
    shell: "terraform-inventory -u ubuntu -k testkey.pem -b 172.24.4.7"
    register: output
  - debug:
      var: task_result