---
- name: "test the connectivity"
  hosts: all
  sudo: yes
  tasks:
  - name: test connectivity
    ping:
    register: task_result
    until: task_result.failed
    retries: 5
    delay: 1
    ignore_errors: True

  - name: debug
    debug:
      msg: " {{ task_result }} "


- name: "testing"
  hosts: vm2
  sudo: yes

  tasks:
  - name: Install apache
    apt:
      update_cache: true
    apt:
      name: apache2
      state: present
*/
