---
- name: "test the connectivity"
  hosts: all
  sudo: yes
  tasks:
  - name: test connectivity
    ping:
    register: task_result
    #command: echo {{ task_result }}
    #until: task_result == "pong"
    #retries: 5
    #delay: 1

- name: "testing"
  hosts: vm2
  sudo: yes

  tasks:
  - name: Install apache
    apt:
      update_cache: true
    apt:
      name: apache2
      state: present
