---
- name: "test the connectivity"
  hosts: all 
  sudo: yes
  gather_facts: false
  
  tasks:

  - name: wait
    local_action: wait_for host="{{ inventory_hostname }}" port=22 delay=10 timeout=120

  - name: test connectivity
    ping:
    register: task_result
    ignore_errors: True

