---
- hosts: all
  gather_facts: false
  force_handlers: true
  any_errors_fatal: false

  tasks:
    - meta: clear_host_errors

    - ping:
      register: task_result
      until: task_result.changed == false
      retries: 10
      delay: 1
      ignore_unreachable: true
      ignore_errors: true

    - debug:
        var: task_result


- name: "testing"
  hosts: vm2
  become: yes

  tasks:
  - name: Install apache
    apt:
      update_cache: true
    apt:
      name: apache2
      state: present
