---
- name: "testing"
  gather_facts: false
  become: true
  hosts: vm1

  tasks:
  - name: curl query
    shell: "curl 192.168.1.3"
    ignore_errors: true
    register: task_result

  - debug:
      var: task_result