---
- name: "testing"
  gather_facts: false
  become: true
  hosts: bastionvm

  tasks:
  - name: curl query
    shell: "curl {{ server_ip }} "
    ignore_errors: true
    register: task_result

  - debug:
      var: task_result
